# Generated by Django 4.1.1 on 2022-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=1000)),
                ('intended_action', models.CharField(max_length=500)),
                ('side_effects', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=500)),
                ('appointment', models.CharField(max_length=500)),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
    ]
