# Generated by Django 4.1.1 on 2022-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cooperative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=1000)),
                ('intended_action', models.CharField(max_length=500)),
                ('side_effects', models.CharField(max_length=500)),
            ],
        ),
    ]
