# Generated by Django 4.1.1 on 2022-10-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_cooperative', '0002_db_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
    ]
